# =============================================================================
# File Name : pygount_summary.py
# Artifact  : LearningClock - Pygount Summary Generator
# Author    : javaboy-vk
# Date      : 2026-06-09
# Version   : v0.1.0
# Purpose:
#   Generates a pygount summary text report, renders a blue terminal-style SVG,
#   and keeps the README code inventory section at the bottom of the file.
# =============================================================================

from __future__ import annotations

import html
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD_REPORT_DIR = ROOT / "build" / "reports"
ASSET_DIR = ROOT / "docs" / "assets"
SUMMARY_TEXT = BUILD_REPORT_DIR / "pygount-summary.txt"
SUMMARY_SVG = ASSET_DIR / "pygount-summary.svg"
README = ROOT / "README.md"
README_SECTION_TITLE = "## Code Inventory"
README_SECTION = f"""\
{README_SECTION_TITLE}

This snapshot is generated by:

```cmd
scripts\\pygount-summary.cmd
```

![Pygount summary](docs/assets/pygount-summary.svg)
"""

def pygount_executable() -> Path:

    executable = ROOT / ".venv" / "Scripts" / "pygount.exe"
    if executable.exists():
        return executable
    found = shutil.which("pygount")
    if found:
        return Path(found)
    raise SystemExit(
        "pygount is not installed. Run scripts\\dev.cmd install, then rerun "
        "scripts\\pygount-summary.cmd."
    )


def git_tracked_files() -> list[str]:

    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    tracked_files = [
        path.decode("utf-8")
        for path in result.stdout.split(b"\0")
        if path and (ROOT / path.decode("utf-8")).is_file()
    ]
    if not tracked_files:
        raise SystemExit("No Git-tracked files were found for the pygount summary.")
    return tracked_files


def run_pygount() -> str:

    command = [str(pygount_executable()), "--format=summary", *git_tracked_files()]
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout.rstrip() + "\n"


def render_svg(summary_text: str) -> str:

    lines = summary_text.rstrip().splitlines()
    if not lines:
        lines = ["No pygount output."]

    font_size = 15
    line_height = 18
    padding_x = 14
    padding_y = 12
    char_width = 8.7
    width = int(max(len(line) for line in lines) * char_width + padding_x * 2)
    height = int(len(lines) * line_height + padding_y * 2)

    text_lines = []
    for index, line in enumerate(lines):
        y = padding_y + font_size + index * line_height
        text_lines.append(
            f'<text x="{padding_x}" y="{y}" xml:space="preserve">{html.escape(line)}</text>'
        )

    return "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}" role="img" aria-label="Pygount summary">',
            f'<rect x="0" y="0" width="{width}" height="{height}" fill="#0b3bdc"/>',
            f'<rect x="4" y="4" width="{width - 8}" height="{height - 8}" '
            'fill="none" stroke="#ffffff" stroke-width="2"/>',
            f'<g fill="#ffffff" font-family="Consolas, Cascadia Mono, Courier New, monospace" '
            f'font-size="{font_size}">',
            *text_lines,
            "</g>",
            "</svg>",
            "",
        ]
    )


def update_readme() -> None:

    text = README.read_text(encoding="utf-8").rstrip()
    existing_index = text.find(f"\n{README_SECTION_TITLE}\n")
    if existing_index != -1:
        text = text[:existing_index].rstrip()
    README.write_text(text + "\n\n" + README_SECTION, encoding="utf-8")


def main() -> int:

    summary_text = run_pygount()
    BUILD_REPORT_DIR.mkdir(parents=True, exist_ok=True)
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    SUMMARY_TEXT.write_text(summary_text, encoding="utf-8")
    SUMMARY_SVG.write_text(render_svg(summary_text), encoding="utf-8")
    update_readme()
    print(f"wrote {SUMMARY_TEXT.relative_to(ROOT)}")
    print(f"wrote {SUMMARY_SVG.relative_to(ROOT)}")
    print(f"updated {README.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
